#!/usr/bin/with-contenv bash

# make folders
[[ ! -d /config/cfg ]] && cp -pr /defaults/cfg /config/cfg
[[ ! -d /config/certs ]] && cp -pr /defaults/certs /config/certs
[[ ! -d /config/log ]] && cp -pr /defaults/log /config/log
[[ ! -d /config/lang ]] && cp -pr /defaults/lang /config/lang
[[ ! -d /config/scripts ]] && cp -pr /app/scripts /config/scripts
[[ ! -f /config/certs/cacert.pem ]] && cd /config/certs && ./make_cert.sh

# copy config files/set links etc...
[[ ! -L /app/cfg ]] && ln -s /config/cfg /app/cfg
[[ ! -L /app/certs ]] && ln -s /config/certs /app/certs
[[ ! -L /app/log ]] && ln -s /config/log /app/log
[[ ! -L /app/scripts ]] && ln -s /config/scripts /app/scripts/
[[ ! -L /app/scripts/lang ]] && ln -s /config/lang /app/scripts/lang

# set perms
#chown abc:abc -R /config /detach_sess
