#!/usr/bin/with-contenv bash

# make folders
[[ ! -d /luadch/cfg ]] && cp -pr /defaults/cfg /config
[[ ! -d /luadch/certs ]] && cp -pr /defaults/certs /config
[[ ! -d /luadch/log ]] && cp -pr /defaults/log /config
[[ ! -d /luadch/lang ]] && cp -pr /defaults/lang /config
[[ ! -f /luadch/certs/cacert.pem ]] && cd /config/certs && ./make_cert.sh

# copy config files/set links etc...
[[ ! -L /luadch/cfg ]] && ln -s /config/cfg /luadch/cfg
[[ ! -L /luadch/certs ]] && ln -s /config/certs /luadch/certs
[[ ! -L /luadch/log ]] && ln -s /config/log /luadch/log
[[ ! -L /luadch/scripts/ ]] && ln -s /config/lang /luadch/scripts/

# set perms
#chown abc:abc -R /config /detach_sess
